## Variable Assignment

In [5]:
a <- 3 + 3

In [6]:
print (a)

[1] 6


In [7]:
greetings <- "hey, buddy!"

In [8]:
print(greetings)

[1] "hey, buddy!"


In [9]:
some_logic <- TRUE

## The Vector

In [11]:
dat <- c(4,5,6,23,2)

In [12]:
print(dat)

[1]  4  5  6 23  2


In [15]:
v1 <- c(1,2,3)
v2 <- c(5,4,3)
v <- c(v1, v2)

In [16]:
print(v)

[1] 1 2 3 5 4 3


In [17]:
my_vec <- rep(0,10)

In [18]:
print(my_vec)

 [1] 0 0 0 0 0 0 0 0 0 0


In [27]:
m <- 1:20

In [28]:
m

[1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20

In [22]:
v3 <- seq(-10, 10, 2)

In [23]:
v3

[1] -10  -8  -6  -4  -2   0   2   4   6   8  10

In [32]:
u <- -2:2

In [33]:
u

[1] -2 -1  0  1  2

## Indexing and Slicing

In [34]:
v <- rnorm(5)

In [35]:
v

[1] -0.009824738  1.447523641 -2.199231313  1.190558812  0.160455861

In [36]:
v[2]

[1] 1.447524

In [37]:
v [1:3]

[1] -0.009824738  1.447523641 -2.199231313

In [38]:
v[2:5]

[1]  1.4475236 -2.1992313  1.1905588  0.1604559

In [39]:
v[c(1,3)] # 选择1和3位置的数字

[1] -0.009824738 -2.199231313

In [40]:
print(v)

[1] -0.009824738  1.447523641 -2.199231313  1.190558812  0.160455861


In [41]:
v

[1] -0.009824738  1.447523641 -2.199231313  1.190558812  0.160455861

In [42]:
v[-3]

[1] -0.009824738  1.447523641  1.190558812  0.160455861

## Assignment with Indexing

In [43]:
u <- c(5, 6, 8, 22)

In [44]:
u[1] <- 0

In [45]:
print(u)

[1]  0  6  8 22


In [46]:
u3 <- u[1:3]

In [48]:
print(u3)

[1] 0 6 8


In [50]:
v <- c(10, 20, 30)

In [51]:
v[1:2] <- 0

In [52]:
print(v)

[1]  0  0 30


In [54]:
v1 <- c(10, 20, 30, 40, 50)
v2 <- v1[c(1, 3, 5)]

In [55]:
v2

[1] 10 30 50

In [56]:
v1 <- seq(10, 50, 10) #sequence = 10, 20, 30, 40, 50
idx <- c(TRUE, FALSE, FALSE, TRUE, FALSE) # 选取10和40
v2 <- v1[idx]
print(v2)

[1] 10 40


In [58]:
v <- c(44, 55, 66)
v2 <- v -20
print(v2)

[1] 24 35 46


In [59]:
v / 5

[1]  8.8 11.0 13.2

## Useful Operations on Vectors

In [62]:
v <- rnorm(10)

In [63]:
print(v)

 [1] -0.36996578 -0.11149281  0.17302700  0.11113239  0.17857172  0.73876321
 [7]  0.06554747  0.48946302 -1.43056084  0.33925797


In [64]:
n <- length(v)

In [65]:
print(n)

[1] 10


In [66]:
sum(v)

[1] 0.1837433

In [67]:
max(v)

[1] 0.7387632

In [68]:
min(v)

[1] -1.430561

In [69]:
xbar <- mean(v)

In [70]:
print(xbar)

[1] 0.01837433


In [71]:
s <- sd(v)

In [72]:
print(s)

[1] 0.5936093


## The Matrix

In [73]:
x1 <- c(4, 5, 6)
x2 <- c(55, 55, 7)

In [74]:
m <- cbind(x1, x2)
print (m) # m is a 3*2 matrix

     x1 x2
[1,]  4 55
[2,]  5 55
[3,]  6  7


In [75]:
m2 <- rbind(x1, x2)
print(m2)

   [,1] [,2] [,3]
x1    4    5    6
x2   55   55    7


In [76]:
a <- matrix(0, nrow = 5, ncol = 3)
print(a)

     [,1] [,2] [,3]
[1,]    0    0    0
[2,]    0    0    0
[3,]    0    0    0
[4,]    0    0    0
[5,]    0    0    0


In [77]:
dat <- rnorm(15)

In [84]:
b <- matrix("cy", ncol = 3, nrow = 5)

In [85]:
print(b)

     [,1] [,2] [,3]
[1,] "cy" "cy" "cy"
[2,] "cy" "cy" "cy"
[3,] "cy" "cy" "cy"
[4,] "cy" "cy" "cy"
[5,] "cy" "cy" "cy"


## Indexing in Matrices

In [114]:
dat <- sample(12)

In [115]:
m <- matrix(dat, ncol = 3, nrow = 4)
print(m)

     [,1] [,2] [,3]
[1,]    3   12    9
[2,]   10    1    8
[3,]    5   11    4
[4,]    7    2    6


In [104]:
m[2,3] # row and column

[1] 12

In [105]:
m[1:2]

[1] 7 6

In [106]:
m[1,] # leave blank, all the columns included

[1] 7 9 2

In [108]:
m[1:2, 2] <- 99
print(m)

     [,1] [,2] [,3]
[1,]    7   99    0
[2,]    6   99    0
[3,]    8    1    0
[4,]    5    3    0


In [109]:
num_rows <- nrow(m)
print(num_rows)

[1] 4


In [110]:
colMeans(m)

[1]  6.5 50.5  0.0

In [96]:
colSums(m)

[1]  26 202   0

In [97]:
rowSums(m)

[1] 106 105   9   8

## The DataFrame

In [116]:
id <- seq(4)
score <- rnorm(4)
names <- c("john", "paul", "george", "ringo")
vocals <- c(TRUE, TRUE, FALSE, FALSE)
dset <- data.frame(id, names, score, vocals)

In [117]:
print(dset)

  id  names      score vocals
1  1   john -0.1532992   TRUE
2  2   paul  1.3964215   TRUE
3  3 george  1.5178568  FALSE
4  4  ringo  0.9700562  FALSE


In [118]:
dset[1,2]

[1] john
Levels: george john paul ringo

In [ ]:
a